application: groupmatefinder
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /scripts
  static_dir: scripts

# Twitter Bootstrap
- url: /bootstrap
  static_dir: bootstrap

# Handler for front page
- url: /
  script: groupmatefinder.app

- url: /about
  script: groupmatefinder.app

# All other pages require login
- url: /profile
  script: groupmatefinder.app
  login: required

- url: /modules
  script: groupmatefinder.app
  login: required

- url: /profilingquestions
  script: groupmatefinder.app
  login: required

- url: /groups
  script: groupmatefinder.app
  login: required

- url: /.*
  script: groupmatefinder.app
  login: required

libraries:
- name: jinja2
  version: latest